#!/bin/bash

STATUS=$(cmus-remote -Q | grep -w 'status' | cut -d " " -f 2)
ARTIST=$(cmus-remote -Q | grep -w 'artist' | cut -d " " -f 3-)
ALBUM=$(cmus-remote -Q | grep -w 'album' | cut -d " " -f 3-)
TITLE=$(cmus-remote -Q | grep -w 'title' | cut -d " " -f 3-)
POSITION=$(cmus-remote -Q | grep -w 'position' | cut -d " " -f 2)

if [ -z $(TITLE) ]; then
	
	if [[ $STATUS  = "playing"* ]]; then
		echo -n "   " 
	elif [[ $STATUS = "paused"* ]]; then
		echo -n "    "
	fi

	if [ $(($POSITION / 60)) -lt 10 ]; then echo -n "0"; fi
	echo -n "$(($POSITION / 60)):" 
	if [ $(($POSITION % 60)) -lt 10 ]; then echo -n "0"; fi
	echo -n "$(($POSITION % 60)) | $ARTIST - $ALBUM - $TITLE"

fi

unset TITLE

